// examples/with-nuxt/app.vue
<script setup lang="ts">

interface User {
  firstName: string
  lastName: string
}

const {data: user, pending} = useFetch<User>('https://api.example.com/user')

</script>
<template>
  <div>
    <p v-if="user" id="greeting">Hello, {{ user.firstName }}!</p>
    <p v-if="pending">Loading...</p>
  </div>
</template>

// examples/with-next/app/page.tsx
import { MovieList } from './movieList'

export type User = {
  firstName: string
  lastName: string
}

async function getUser() {
  const response = await fetch('https://api.example.com/user')
  const user = (await response.json()) as User
  return user
}

export default async function Home() {
  const user = await getUser()

  return (
    <main>
      <p id="server-side-greeting">Hello, {user.firstName}!</p>
      <MovieList />
    </main>
  )
}
